---
title: "Loutre"
author: "Pablo"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
#  bookdown::word_docume
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, echo = TRUE, warning = FALSE, message = FALSE)
```

# Importation des packages

```{r}
library(tidyverse)
library(gridExtra)
library(lubridate)
library(sf)
library(mapview)
library(maptiles)
library(tidyterra)
library(kableExtra)
library(knitr)
```

# Importation des données - Secteur J25 : Petit Tregor 

```{r}
base_tregor <-
  readxl::read_xlsx(path = '../raw_data/export_suiviloutrelocal_telecharger_csv_2025_04_03_10h58m17.xlsx') %>%
  dplyr::select(
    id_dataset,
    code_secteur,
    code_site,
    nom_site,
    x_l93,
    y_l93,
    date_visite,
    observateurs,
    condition_prospection,
    nom_taxon,
    nom_complet_taxon,
    techn_observation,
    statut_observation,
    nb_ep_tot,
    nb_ep_w,
    nb_ep_dnf,
    nb_ep_df
  ) %>%
  mutate(
    annee = year(date_visite),
    mois = month(date_visite),
    jour = day(date_visite),
    nb_ep_w = abs(nb_ep_w),
    statut_observation = ifelse(str_detect(statut_observation, '^Pr'), yes = 'Présent', no = 'Absent')
  ) %>% 
  filter(nom_complet_taxon =='Lutra lutra',
         !(id_dataset == 85 & code_secteur == "FR5300006"),
         code_secteur != "J401")
```


# Représentation cartographique des secteurs d'étude et des sites correspondants

```{r, eval = TRUE, fig.width = 9, fig.height = 6}
sites_geo <- base_tregor %>% 
  dplyr::select(nom_site:y_l93,
         statut_observation,
         code_secteur,
         annee) %>% 
  sf::st_as_sf(coords = c("x_l93", "y_l93"),
               crs = sf::st_crs(2154))
 
mapview::mapview(sites_geo, 
                 zcol = "code_secteur",
                 col.regions = c("FR5300006" = "indianred1", 
                                 "J25" = "darkseagreen3") 
)
```


```{r, fig.width = 9, fig.height = 8}

base_j25 <- base_tregor %>%
  filter(code_secteur == "J25")

sites_coord <- base_j25 %>%
  dplyr::select(code_site, x_l93, y_l93) %>%
  distinct()

sites_all_years <- expand_grid(
  code_site = unique(base_j25$code_site),
  annee = unique(base_j25$annee)
)

sites_status_full <- sites_all_years %>%
  left_join(base_j25 %>% 
              select(code_site, annee, statut_observation),
            by = c("code_site", "annee")) %>%
  left_join(sites_coord, by = "code_site") %>%
  mutate(
    statut_final = case_when(
      statut_observation == "Présent" ~ "Présent",
      statut_observation == "Absent" ~ "Absent",
      TRUE ~ "Non prospecté"
    )
  )

sites_j25_sf <- sites_status_full %>%
  st_as_sf(coords = c("x_l93", "y_l93"), crs = 2154)

basemap <- get_tiles(sites_j25_sf, provider = "CartoDB.Positron", crop = TRUE, zoom = 12)

ggplot() +
  geom_spatraster_rgb(data = basemap) +
  geom_sf(data = sites_j25_sf, aes(color = statut_final), size = 1.5, alpha = 0.9) +
  facet_wrap(~ annee) +
  scale_color_manual(
    values = c("Présent" = "darkseagreen3", "Absent" = "indianred1", "Non prospecté" = "grey40")
  ) +
  labs(
    title = "Sites de prospection, Petit Trégor - Secteur Petit Tregor (J25)",
    color = "Statut d'observation"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA),
    strip.background = element_rect(fill = "grey90"),
    legend.background = element_rect(fill = "grey95", color = "black")
  )

```

# Statistiques descriptive


```{r}
summary(base_tregor$date_visite)
```


```{r, fig.cap="Nombre d'observations de présence de la loutre en fonction des années",fig.width = 7, fig.height = 5}
base_j25 %>%
  filter(statut_observation == 'Présent') %>%
  ggplot(aes(x = annee)) +
  geom_bar(fill = "black") +
  labs(x = "Année", 
       y = "Nombre d'observations de présence de la loutre", 
       title = "Suivi des sites de prospection - Secteur Petit Tregor (J25)") +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA)
    )
  
```

```{r,fig.cap="Nombre d'observations de présence et absence de la loutre en fonction des années",fig.width = 7, fig.height = 5}
base_j25 %>%
  ggplot(aes(x = annee, fill = statut_observation)) +
  geom_bar() +
  scale_fill_manual(values = c(
    "Présent" = "darkseagreen3",
    "Absent" = "indianred1"
  )) +
  labs(x = "Année",
       y = "Nombre d'observations de présence  et absence de loutre",
       title = "Suivi des sites de prospection - Secteur Petit Tregor (J25)",
       fill = "Observation") +
  theme (
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA),
    legend.background = element_rect(fill = "grey95", color = "black")
  )
  

```

```{r, fig.cap="Statut d'observation des sites prospectée en fonction des années ",fig.width = 9, fig.height = 7}


base_j25 <- base_j25 %>%
  mutate(annee = year(date_visite))

all_combos <- expand_grid(code_site = unique(base_j25$code_site),
                          annee = unique(base_j25$annee))

obs_complete <- all_combos %>%
  left_join(base_j25 %>% select(code_site, annee, statut_observation),
            by = c("code_site", "annee")) %>%
  mutate(
    statut_final = case_when(
      statut_observation == "Présent" ~ "Présent",
      statut_observation == "Absent" ~ "Absent",
      TRUE ~ "Non prospecté"
    )
  )

ggplot(obs_complete, aes(x = annee, y = code_site, fill = statut_final)) +
  geom_tile(color = "white", linewidth = 0.3) +
  scale_fill_manual(
    values = c(
      "Présent" = "darkseagreen3",
      "Absent" = "indianred1",
      "Non prospecté" = "grey80"
    )
  ) +
  labs(x = "Année",
       y = "Site",
       title = "Suivi des sites de prospection - Secteur Petit Tregor (J25)",
       fill = "Statut d'observation") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA),
    legend.background = element_rect(fill = "grey95", color = "black")
  )
```


```{r,fig.cap="Pourcentages de présence de la loutre en fonction des années",fig.width = 7, fig.height = 5}
base_j25 %>%
  group_by(annee) %>%
  summarise(
    n_obs = n(),
    n_presences = sum(statut_observation == 'Présent'),
    pc_presences = n_presences / n_obs
  ) %>%
  ggplot(aes(x = annee, y = pc_presences)) +
  geom_bar(stat = 'identity') +
  labs(x = "Année", y = "Pourcentage de présence de la loutre", title = "Suivi des sites de prospection - Secteur Petit Tregor (J25)") +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA)
  )

```


