---
title: "31_GLMM_Lieue_de_greve"
author: "PabloVigneron"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  bookdown::html_document2:
   fig_caption: yes
   tab_caption: yes
   number_sections: yes
   global_numbering: yes
   toc: yes
   toc_float:
         toc_collapsed: yes
         toc_depth: 2
   code_folding: hide
   css: "style.css"
bibliography: library_biblio_otter.bib
link-citations: true
cls: apa.cls
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
# Importation des packages
library(tidyverse)
library(gridExtra)
#library(lubridate)
library(sf)
library(mapview)
library(maptiles)
library(tidyterra)
library(kableExtra)
#library(knitr)
library(janitor)
library(RVAideMemoire)
library(emmeans)
library(car)
library(MASS)
library(lme4)
library(MuMIn)
#library(stringr)
library(stringi)
library(terra)
library(ggspatial)
library(slippymath)     
library(rosm)           
library(writexl)
```


```{r}
# Importation avec data 2025 - Lieue de Greve 

base_greve_raw <-
  readxl::read_xls(path = '../raw_data/Suivi loutre mars_25.xls',
                   skip = 1,
                   col_names = T) 
```

```{r}
## Correction des données - Mise en forme - Secteur : Lieu Greve avec data 2025

base_greve <- base_greve_raw %>%
  janitor::clean_names() %>%
  dplyr::select(
    point_n,
    itineraire,
    x,
    y,
    commune,
    cours_deau,
    bilan_choix_du_site,
    epreinte_oct20,
    date_suivi_fev_mars21,
    marquage_suivi_fev_mars21,
    date_suivi_oct21,
    marquage_suivi_oct21,
    observateurs_suivi_oct21,
    date_suivi_mars22,
    marquage_suivi_mars22,
    observateurs_suivi_mars22,
    date_suivi_decembre22,
    marquage_suivi_decembre22,
    observateurs_suivi_decembre22,
    date_suivi_mars23,
    marquage_suivi_mars23,
    observateurs_suivi_mars23,
    date_suivi_octobre_24,
    marquage_suivi_octobre_24,
    observateurs_suivi_octobre_24, 
    date_suivi_mars_25, 
    marquage_suivi_mars_25, 
    observateurs_suivi_mars_25
  ) %>%
  dplyr::rename(
    code_site = point_n,
    y = x,
    x = y,
    marquage_suivi_oct_20 = epreinte_oct20
  ) %>%
  dplyr::mutate(date_suivi_octobre_24 = as.Date(as.numeric(date_suivi_octobre_24), origin = "1899-12-30")) %>%
  dplyr::mutate(date_suivi_oct_20 = as.Date("2020-10-01")) %>%
  dplyr::mutate(across(
    c(
      date_suivi_fev_mars21,
      date_suivi_oct21,
      date_suivi_mars22,
      date_suivi_decembre22,
      date_suivi_mars23,
      date_suivi_oct_20, 
      date_suivi_mars_25
    ),
    ~ as.POSIXct(.x)
  )) %>%
  mutate(across(starts_with("marquage_suivi_"), as.character)) %>%
  tidyr::pivot_longer(
    cols = c(
      date_suivi_oct_20,
      marquage_suivi_oct_20,
      date_suivi_fev_mars21,
      marquage_suivi_fev_mars21,
      date_suivi_oct21,
      marquage_suivi_oct21,
      observateurs_suivi_oct21,
      date_suivi_mars22,
      marquage_suivi_mars22,
      observateurs_suivi_mars22,
      date_suivi_decembre22,
      marquage_suivi_decembre22,
      observateurs_suivi_decembre22,
      date_suivi_mars23,
      marquage_suivi_mars23,
      observateurs_suivi_mars23,
      date_suivi_octobre_24,
      marquage_suivi_octobre_24,
      observateurs_suivi_octobre_24, 
      date_suivi_mars_25, 
      marquage_suivi_mars_25,
      observateurs_suivi_mars_25
    ),
    names_to = c(".value", "session"),
    names_pattern = "(date_suivi|marquage_suivi|observateurs_suivi)_(.*)"
  ) %>%
  rename(
    date_visite = date_suivi,
    statut_presence = marquage_suivi,
    observateurs = observateurs_suivi
  ) %>%
  dplyr::mutate(
    annee = year(date_visite),
    mois = month(date_visite),
    jour = day(date_visite),
    code_site = as.factor(code_site),
    statut_presence = case_when(
      tolower(statut_presence) == "oui" ~ 1,
      suppressWarnings(as.numeric(statut_presence)) >= 1 ~ 1,
      tolower(statut_presence) %in% c("non", "peut_etre") ~ 0,
      TRUE ~ 0
    ),
    statut_observation = ifelse(statut_presence == 1, "Présent", "Absent"),
    statut_presence = as.factor (statut_presence),
    jour = ifelse(jour == 1, NA, jour),
    annee = ifelse(annee == 2002, 2021, annee),
    y = str_replace_all(y, ",", ""),
    x = str_replace_all(x, " ", ""),
    passage = ifelse(mois <= 6, 1, 2),
    date_visite = ifelse(
      date_visite == as.Date("2002-02-24"),
      "2021-02-24",
      as.character(date_visite)
    ),
    observateurs_clean = observateurs %>%
      str_to_lower() %>%
      str_replace_all(" et ", "_") %>%
      str_replace_all("[[:space:]]+", "_") %>%
      str_replace_all("[^a-z0-9_]", "") %>%
      stri_trans_general("latin-ascii")
  ) %>%
  dplyr::mutate(observateurs_clean = as.factor(
    ifelse(
      observateurs_clean == "maxime_chapelle_romain_salaun",
      "maxime_chapelle_romain_salun",
      observateurs_clean
    )
  )) %>%
  dplyr::filter(!is.na(code_site), !is.na(itineraire))


```

## Modele 1 : Le statut de présence dépend de l'année (numeric) 
```{r}
greve_year_numeric_season <- base_greve%>%
  mutate(annee = as.numeric(annee), 
         passage = as.factor(passage), 
         mois = as.factor(mois))
```


```{r}
mod1.0<- glmer(statut_presence~annee + (1|code_site), family=binomial(link = "logit"), data = greve_year_numeric_season)

plotresid(mod1.0)
```

```{r}
summary(mod1.0)
```

## Modele 2 : Le statut de présence dépend de l'année (numeric) et de la saison

```{r}
mod2.0<- glmer(statut_presence~annee + passage + (1|code_site), family=binomial(link = "logit"), data = greve_year_numeric_season)

plotresid(mod2.0)

```

```{r}
summary(mod2.0)
```

## Modele 3 : Le statut de présence dépend de l'année (factor) et de la saison

```{r}
greve_year_factor_season <- base_greve%>%
  mutate(annee = as.factor(annee), 
         passage = as.factor(passage))
```

```{r}
mod3.0 <- glmer(statut_presence ~ annee + passage + (1|code_site), 
                family = binomial(link = "logit"), 
                data = greve_year_factor_season)
plotresid(mod3.0)
```
# sauvegarde des données prétraitées

```{r}
save(greve_year_numeric_season,
     file = "../processed_data/greve_year_numeric_season.rda")
```

